### ISSUE TITLE
run_tests.py failing - appears pyvshadow related

### ISSUE THREAD

**Issue by gregfreemyer** [log2timeline/dfvfs#100]
dfVFS  20160108
pyvshadow 20160109

run from "/tmp/dfvfs-20160108" (so long paths is not an issue)

The failed tests all end with:
```
AttributeError: 'pyvshadow.store' object has no attribute 'has_in_volume_data'
```

The final output from "run_tests.py" is:
```
======================================================================
ERROR: testScan (helpers.source_scanner.SourceScannerTest)
Test the Scan() function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dfvfs-20160108/tests/helpers/source_scanner.py", line 93, in testScan
    self._source_scanner.Scan(scan_context, scan_path_spec=scan_node.path_spec)
  File "./dfvfs/helpers/source_scanner.py", line 564, in Scan
    self._ScanNode(scan_context, scan_node, auto_recurse=auto_recurse)
  File "./dfvfs/helpers/source_scanner.py", line 487, in _ScanNode
    source_path_spec = self.ScanForFileSystem(scan_node.path_spec)
  File "./dfvfs/helpers/source_scanner.py", line 583, in ScanForFileSystem
    source_path_spec, resolver_context=self._resolver_context)
  File "./dfvfs/analyzer/analyzer.py", line 295, in GetFileSystemTypeIndicators
    resolver_context=resolver_context)
  File "./dfvfs/analyzer/analyzer.py", line 188, in _GetTypeIndicators
    path_spec, resolver_context=resolver_context)
  File "./dfvfs/resolver/resolver.py", line 113, in OpenFileObject
    file_object.open(path_spec=path_spec)
  File "./dfvfs/file_io/file_io.py", line 73, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "./dfvfs/file_io/vshadow_file_io.py", line 68, in _Open
    if not vshadow_store.has_in_volume_data():
AttributeError: 'pyvshadow.store' object has no attribute 'has_in_volume_data'

======================================================================
ERROR: testScanForFileSystem (helpers.source_scanner.SourceScannerTest)
Test the ScanForFileSystem() function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dfvfs-20160108/tests/helpers/source_scanner.py", line 208, in testScanForFileSystem
    path_spec = self._source_scanner.ScanForFileSystem(source_path_spec)
  File "./dfvfs/helpers/source_scanner.py", line 583, in ScanForFileSystem
    source_path_spec, resolver_context=self._resolver_context)
  File "./dfvfs/analyzer/analyzer.py", line 295, in GetFileSystemTypeIndicators
    resolver_context=resolver_context)
  File "./dfvfs/analyzer/analyzer.py", line 188, in _GetTypeIndicators
    path_spec, resolver_context=resolver_context)
  File "./dfvfs/resolver/resolver.py", line 113, in OpenFileObject
    file_object.open(path_spec=path_spec)
  File "./dfvfs/file_io/file_io.py", line 73, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "./dfvfs/file_io/vshadow_file_io.py", line 68, in _Open
    if not vshadow_store.has_in_volume_data():
AttributeError: 'pyvshadow.store' object has no attribute 'has_in_volume_data'

======================================================================
ERROR: testGetFileSystemTypeIndicators (analyzer.analyzer.AnalyzerTest)
Function to test the get file system type indicators function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dfvfs-20160108/tests/analyzer/analyzer.py", line 74, in testGetFileSystemTypeIndicators
    path_spec)
  File "./dfvfs/analyzer/analyzer.py", line 295, in GetFileSystemTypeIndicators
    resolver_context=resolver_context)
  File "./dfvfs/analyzer/analyzer.py", line 188, in _GetTypeIndicators
    path_spec, resolver_context=resolver_context)
  File "./dfvfs/resolver/resolver.py", line 113, in OpenFileObject
    file_object.open(path_spec=path_spec)
  File "./dfvfs/file_io/file_io.py", line 73, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "./dfvfs/file_io/vshadow_file_io.py", line 68, in _Open
    if not vshadow_store.has_in_volume_data():
AttributeError: 'pyvshadow.store' object has no attribute 'has_in_volume_data'

======================================================================
ERROR: testOpenClose (file_io.vshadow_file_io.VShadowFileTest)
Test the open and close functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dfvfs-20160108/tests/file_io/vshadow_file_io.py", line 32, in testOpenClose
    file_object.open(path_spec=path_spec)
  File "./dfvfs/file_io/file_io.py", line 73, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "./dfvfs/file_io/vshadow_file_io.py", line 68, in _Open
    if not vshadow_store.has_in_volume_data():
AttributeError: 'pyvshadow.store' object has no attribute 'has_in_volume_data'

======================================================================
ERROR: testRead (file_io.vshadow_file_io.VShadowFileTest)
Test the read functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dfvfs-20160108/tests/file_io/vshadow_file_io.py", line 116, in testRead
    file_object.open(path_spec=path_spec)
  File "./dfvfs/file_io/file_io.py", line 73, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "./dfvfs/file_io/vshadow_file_io.py", line 68, in _Open
    if not vshadow_store.has_in_volume_data():
AttributeError: 'pyvshadow.store' object has no attribute 'has_in_volume_data'

======================================================================
ERROR: testSeek (file_io.vshadow_file_io.VShadowFileTest)
Test the seek functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dfvfs-20160108/tests/file_io/vshadow_file_io.py", line 71, in testSeek
    file_object.open(path_spec=path_spec)
  File "./dfvfs/file_io/file_io.py", line 73, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "./dfvfs/file_io/vshadow_file_io.py", line 68, in _Open
    if not vshadow_store.has_in_volume_data():
AttributeError: 'pyvshadow.store' object has no attribute 'has_in_volume_data'

----------------------------------------------------------------------
Ran 389 tests in 26.678s

FAILED (errors=6)
```

**Comment by joachimmetz** [comment]
Which version of libvshadow are you using?

**Comment by joachimmetz** [comment]
has_in_volume_data was introduced on: 20160109 see:
https://github.com/libyal/libvshadow/commit/23d8791724302326f696621388dfbc16cc83c703

@gregfreemyer can try upgrading libvshadow to 20160110.

**Comment by gregfreemyer** [comment]
with libvshadow 20160110 it runs clean.  If you update check_dependencies you can close this.

Thanks, Greg

**Comment by joachimmetz** [comment]
![Challenge to be considered](http://memes.dafunnies.net/faces/large/determined-challenge-considered-l.png)

**Comment by joachimmetz** [comment]
Pending change in https://codereview.appspot.com/288010043/
