### ISSUE TITLE
Issues with the signature scan

### ISSUE THREAD

**Issue by kiddinn** [log2timeline/dfvfs#16]
Latest version of plaso
 + log2timeline - plaso back-end 1.2.1_20150225
 + dfvfs - 20150224
 + libsigscan - 20150125

```
    2015-02-25 17:45:27,094 [WARNING] (Worker_2  ) PID:13288 <worker> [skydrive_log] Unable to process file: type: OS, location: /PATH/bde/bde1
    type: RAW
    type: TSK, inode: 118222, location: /Users/<FOO>/AppData/Local/Microsoft/Windows/Temporary Internet Files/Low/Content.IE5/0VUCKP34/AccountChooser[1].htm
    type: GZIP
    with error: Unable to decompress zlib compressed stream with error: Error -3 while decompressing: invalid distance too far back..
```

```
2015-02-25 17:45:27,094 [ERROR] (Worker_2  ) PID:13288 <worker> Unable to decompress zlib compressed stream with error: Error -3 while decompressing: invalid distance too far back.
Traceback (most recent call last):
 File "/usr/lib/python2.7/dist-packages/plaso/engine/worker.py", line 146, in _ParseFileEntryWithParser
   parser_object.UpdateChainAndParse(self._parser_mediator)
 File "/usr/lib/python2.7/dist-packages/plaso/parsers/interface.py", line 71, in UpdateChainAndParse
   self.Parse(parser_mediator, **kwargs)
 File "/usr/lib/python2.7/dist-packages/plaso/parsers/text_parser.py", line 741, in Parse
   text_file_object = text_file.TextFile(file_object)
 File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/text_file.py", line 32, in __init__
   self._file_object_size = file_object.get_size()
 File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/file_object_io.py", line 151, in get_size
   return self._file_object.get_size()
 File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py", line 314, in get_size
   self._uncompressed_stream_size = self._GetUncompressedStreamSize()
 File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py", line 90, in _GetUncompressedStreamSize
   read_count = self._ReadCompressedData(self._COMPRESSED_DATA_BUFFER_SIZE)
 File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py", line 173, in _ReadCompressedData
   self._decompressor.Decompress(self._compressed_data))
```

**Comment by joachimmetz** [comment]
Try updating libbde

**Comment by kiddinn** [comment]
[OK]		libbde (pybde) version: 20150204
[OK]		libesedb (pyesedb) version: 20141110
[OK]		libevt (pyevt) version: 20150105
[OK]		libevtx (pyevtx) version: 20150105
[INFO]		libewf (pyewf) version: 20140608 installed, version: 20150126 available.
[OK]		libfwsi (pyfwsi) version: 20150124
[OK]		liblnk (pylnk) version: 20150105
[OK]		libmsiecf (pymsiecf) version: 20150106
[OK]		libolecf (pyolecf) version: 20150106
[OK]		libqcow (pyqcow) version: 20150105
[OK]		libregf (pyregf) version: 20150105
[OK]		libsigscan (pysigscan) version: 20150125
[OK]		libsmdev (pysmdev) version: 20150105
[OK]		libsmraw (pysmraw) version: 20150105
[INFO]		libvhdi (pyvhdi) version: 20150105 installed, version: 20150110 available.
[OK]		libvmdk (pyvmdk) version: 20150105
[OK]		libvshadow (pyvshadow) version: 20150106


and this was of course supposed to be filed in plaso, not dfrvs

**Comment by joachimmetz** [comment]
I'll have a look.

**Comment by joachimmetz** [comment]
Is this still an issue?
