### ISSUE TITLE
Issue with imagefiles fontaing UTF-8 characters in path

### ISSUE THREAD

**Issue by eoyslebo** [log2timeline/dfvfs#160]
Working through some examples at a blog about automating DFIR with dfVFS, I had an issue with dfVFS if the image file path contains UTF-8 characters (/mnt/imagefiles/tromsø.E01).

Renaming (or even symlinking to) the file resolves the issue as a workaround.

I reported a [possibly related issue](https://github.com/log2timeline/plaso/issues/351) with plaso a while back which has been resolved.

```
import sys
import logging
from dfvfs.analyzer import analyzer
from dfvfs.lib import definitions
from dfvfs.path import factory as path_spec_factory
from dfvfs.volume import tsk_volume_system
from dfvfs.resolver import resolver
from dfvfs.lib import raw
source_path="/mnt/imagefiles/tromsø.E01"
path_spec = path_spec_factory.Factory.NewPathSpec(
          definitions.TYPE_INDICATOR_OS, location=source_path)
type_indicators = analyzer.Analyzer.GetStorageMediaImageTypeIndicators(
          path_spec)
```

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python2.7/dist-packages/dfvfs/analyzer/analyzer.py", line 324, in GetStorageMediaImageTypeIndicators
    resolver_context=resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/analyzer/analyzer.py", line 188, in _GetTypeIndicators
    path_spec, resolver_context=resolver_context)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/resolver.py", line 103, in OpenFileObject
    file_object = resolver_context.GetFileObject(path_spec)
  File "/usr/lib/python2.7/dist-packages/dfvfs/resolver/context.py", line 96, in GetFileObject
    return self._file_object_cache.GetObject(path_spec.comparable)
  File "/usr/lib/python2.7/dist-packages/dfvfs/path/location_path_spec.py", line 32, in comparable
    sub_comparable_string = u'location: {0:s}'.format(self.location)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
```

**Comment by joachimmetz** [comment]
Try defining your source path as Unicode, not as an encoded byte stream

```
source_path=u"/mnt/imagefiles/tromsø.E01"
```

**Comment by eoyslebo** [comment]
That worked. Thank you :)
