### ISSUE TITLE
Log2timeline.py cannot process source when it is a symlink to a directory

### ISSUE THREAD

**Issue by rgayon** [log2timeline/dfvfs#171]
```
$ python tools/log2timeline.py --version
plaso - log2timeline version 1.5.1_20161013
$ python tools/log2timeline.py --status_view none /tmp/test.plaso /tmp/test
Checking availability and versions of dependencies.
[OK]


Source path     : /tmp/test
Source type     : directory

Processing started.
2016-10-14 17:04:04,160 [INFO] (MainProcess) PID:7292 <engine> Preprocessing detected platform: Unknown
2016-10-14 17:04:04,160 [INFO] (MainProcess) PID:7292 <extraction_frontend> Setting timezone to: UTC
2016-10-14 17:04:11,858 [INFO] (MainProcess) PID:7292 <zeromq_queue> Queue main_task_queue responder exiting.
Processing completed.
```

`$ ln -s /tmp/test /tmp/test2`

```
$ python tools/log2timeline.py /tmp/test.plaso /tmp/test2
Checking availability and versions of dependencies.
[OK]

Traceback (most recent call last):
  File "tools/log2timeline.py", line 767, in <module>
    if not Main():
  File "tools/log2timeline.py", line 753, in Main
    tool.ProcessSources()
  File "tools/log2timeline.py", line 612, in ProcessSources
    scan_context = self.ScanSource()
  File "/usr/local/google/home/romaing/dev/plaso/plaso/cli/storage_media_tool.py", line 1084, in ScanSource
    self._source_scanner.Scan(scan_context)
  File "/usr/local/google/home/romaing/dev/dfvfs/dfvfs/helpers/source_scanner.py", line 563, in Scan
    self._ScanNode(scan_context, scan_node, auto_recurse=auto_recurse)
  File "/usr/local/google/home/romaing/dev/dfvfs/dfvfs/helpers/source_scanner.py", line 373, in _ScanNode
    source_path_spec = self.ScanForStorageMediaImage(scan_node.path_spec)
  File "/usr/local/google/home/romaing/dev/dfvfs/dfvfs/helpers/source_scanner.py", line 622, in ScanForStorageMediaImage
    source_path_spec, resolver_context=self._resolver_context)
  File "/usr/local/google/home/romaing/dev/dfvfs/dfvfs/analyzer/analyzer.py", line 340, in GetStorageMediaImageTypeIndicators
    resolver_context=resolver_context)
  File "/usr/local/google/home/romaing/dev/dfvfs/dfvfs/analyzer/analyzer.py", line 185, in _GetTypeIndicators
    path_spec, resolver_context=resolver_context)
  File "/usr/local/google/home/romaing/dev/dfvfs/dfvfs/resolver/resolver.py", line 116, in OpenFileObject
    file_object.open(path_spec=path_spec_object)
  File "/usr/local/google/home/romaing/dev/dfvfs/dfvfs/file_io/file_io.py", line 68, in open
    self._Open(path_spec=path_spec, mode=mode)
  File "/usr/local/google/home/romaing/dev/dfvfs/dfvfs/file_io/os_file_io.py", line 100, in _Open
    self._file_object = open(location, mode=mode)
IOError: [Errno 21] Is a directory: u'/tmp/test2'

```

**Comment by joachimmetz** [comment]
Plaso issue, moved to https://github.com/log2timeline/plaso/issues/1473
