### ISSUE TITLE
Problem with RAW images in python3

### ISSUE THREAD

**Issue by tincho9** [log2timeline/dfvfs#177]
H, I have the following exception in python3, while trying to handle a RAW image, while the same code on python2.7 runs fine:
`Traceback (most recent call last):
  File "dfvfs_tesing.py", line 100, in <module>
    volume_system.Open(volume_path_spec)
  File "/home/martin/.local/lib/python3.5/site-packages/dfvfs/volume/tsk_volume_system.py", line 98, in Open
    self._file_system = resolver.Resolver.OpenFileSystem(path_spec)
  File "/home/martin/.local/lib/python3.5/site-packages/dfvfs/resolver/resolver.py", line 173, in OpenFileSystem
    file_system.Open(path_spec_object)
  File "/home/martin/.local/lib/python3.5/site-packages/dfvfs/vfs/file_system.py", line 231, in Open
    self._Open(path_spec, mode=mode)
  File "/home/martin/.local/lib/python3.5/site-packages/dfvfs/vfs/tsk_partition_file_system.py", line 63, in _Open
    path_spec.parent, resolver_context=self._resolver_context)
  File "/home/martin/.local/lib/python3.5/site-packages/dfvfs/resolver/resolver.py", line 111, in OpenFileObject
    u'{0:s}.').format(path_spec_object.type_indicator))
KeyError: 'Resolver helper object not set for type indicator: RAW.'
`

When I fire up ipdb, and print the list of cls._resolver_helpers, RAW is indeed not present:
`{'TSK': <dfvfs.resolver.tsk_resolver_helper.TSKResolverHelper object at 0x7f1716a4ff28>, 'DATA_RANGE': <dfvfs.resolver.data_range_resolver_helper.DataRangeResolverHelper object at 0x7f1716b76a58>, 'ENCRYPTED_STREAM': <dfvfs.resolver.encrypted_stream_resolver_helper.EncryptedStreamResolverHelper object at 0x7f17168c5e80>, 'COMPRESSED_STREAM': <dfvfs.resolver.compressed_stream_resolver_helper.CompressedStreamResolverHelper object at 0x7f1716b9fa90>, 'ENCODED_STREAM': <dfvfs.resolver.encoded_stream_resolver_helper.EncodedStreamResolverHelper object at 0x7f17168c5a58>, 'TSK_PARTITION': <dfvfs.resolver.tsk_partition_resolver_helper.TSKPartitionResolverHelper object at 0x7f1717a80438>, 'CPIO': <dfvfs.resolver.cpio_resolver_helper.CPIOResolverHelper object at 0x7f1716b955c0>, 'TAR': <dfvfs.resolver.tar_resolver_helper.TARResolverHelper object at 0x7f1717a71b38>, 'GZIP': <dfvfs.resolver.gzip_resolver_helper.GzipResolverHelper object at 0x7f17168eec50>, 'FAKE': <dfvfs.resolver.fake_resolver_helper.FakeResolverHelper object at 0x7f1716b8cef0>, 'VSHADOW': <dfvfs.resolver.vshadow_resolver_helper.VShadowResolverHelper object at 0x7f1716a6c400>, 'SQLITE_BLOB': <dfvfs.resolver.sqlite_blob_resolver_helper.SQLiteBlobResolverHelper object at 0x7f17168c5b00>, 'ZIP': <dfvfs.resolver.zip_resolver_helper.ZipResolverHelper object at 0x7f1716a7d8d0>, 'OS': <dfvfs.resolver.os_resolver_helper.OSResolverHelper object at 0x7f17168fa9e8>}`

For reference in python2.7 it does appear:
{u'BDE': <dfvfs.resolver.bde_resolver_helper.BDEResolverHelper object at 0x7fca3deef410>, u'SQLITE_BLOB': <dfvfs.resolver.sqlite_blob_resolver_helper.SQLiteBlobResolverHelper object at 0x7fca3d233290>, u'VSHADOW': <dfvfs.resolver.vshadow_resolver_helper.VShadowResolverHelper object at 0x7fca3d1efd90>, u'COMPRESSED_STREAM': <dfvfs.resolver.compressed_stream_resolver_helper.CompressedStreamResolverHelper object at 0x7fca3deff410>, u'TSK': <dfvfs.resolver.tsk_resolver_helper.TSKResolverHelper object at 0x7fca3d1ef0d0>, u'TAR': <dfvfs.resolver.tar_resolver_helper.TarResolverHelper object at 0x7fca3d233710>, u'VHDI': <dfvfs.resolver.vhdi_resolver_helper.VHDIResolverHelper object at 0x7fca3d1ef390>, u'TSK_PARTITION': <dfvfs.resolver.tsk_partition_resolver_helper.TSKPartitionResolverHelper object at 0x7fca3d1d8290>, u'ENCODED_STREAM': <dfvfs.resolver.encoded_stream_resolver_helper.EncodedStreamResolverHelper object at 0x7fca3da764d0>, u'DATA_RANGE': <dfvfs.resolver.data_range_resolver_helper.DataRangeResolverHelper object at 0x7fca3deff710>, u'EWF': <dfvfs.resolver.ewf_resolver_helper.EWFResolverHelper object at 0x7fca3da8c710>, u'QCOW': <dfvfs.resolver.qcow_resolver_helper.QCOWResolverHelper object at 0x7fca3d20ea90>, **u'RAW': <dfvfs.resolver.raw_resolver_helper.RawResolverHelper object at 0x7fca3d20ed90>,** u'NTFS': <dfvfs.resolver.ntfs_resolver_helper.NTFSResolverHelper object at 0x7fca3d25ffd0>, u'VMDK': <dfvfs.resolver.vmdk_resolver_helper.VMDKResolverHelper object at 0x7fca3d1ef810>, u'FAKE': <dfvfs.resolver.fake_resolver_helper.FakeResolverHelper object at 0x7fca3da8c790>, u'GZIP': <dfvfs.resolver.gzip_resolver_helper.GzipResolverHelper object at 0x7fca3d254550>, u'ZIP': <dfvfs.resolver.zip_resolver_helper.ZipResolverHelper object at 0x7fca3d1807d0>, u'OS': <dfvfs.resolver.os_resolver_helper.OSResolverHelper object at 0x7fca3d1fe650>, u'ENCRYPTED_STREAM': <dfvfs.resolver.encrypted_stream_resolver_helper.EncryptedStreamResolverHelper object at 0x7fca3da8c210>}

Help is really appreciated.

**Comment by tincho9** [comment]
I was mising pysmraw from https://github.com/libyal/libsmraw

everything is fine now :)
