### ISSUE TITLE
EncryptedStream: decrypted_stream_size is not set during seek.

### ISSUE THREAD

**Issue by dc3-plaso** [log2timeline/dfvfs#183]
version: 20161113
installation: pip

When using the EncryptedStream file_io class, I get a `TypeError` if I attempt to perform a seek with a `os.SEEK_END` whence before running a read(). This is due to the `self._decrypted_stream_size` not getting set.

```python
import os
import io
from Crypto.Cipher import AES
		
from dfvfs.file_io import encrypted_stream_io
from dfvfs.path import encrypted_stream_path_spec, fake_path_spec
from dfvfs.resolver import context

key = 'This is a key123'
iv = 'This is an IV456'
data = 'A secret!!!!!!!!'
cipher = AES.new(key, AES.MODE_CBC, iv)
enc_data = cipher.encrypt(data)

enc_file_object = io.BytesIO(enc_data)
enc_file_object.get_size = lambda : len(enc_data)

path_spec = encrypted_stream_path_spec.EncryptedStreamPathSpec(
	cipher_mode=u'cbc', encryption_method=u'aes', initialization_vector=iv, key=key, 
	parent=fake_path_spec.FakePathSpec('blah'))
file_object = encrypted_stream_io.EncryptedStream(context.Context(), encryption_method=u'aes', file_object=enc_file_object)

file_object.open(path_spec)
file_object.seek(-3, os.SEEK_END)
print file_object.read()
```

Causes:
```python
Traceback (most recent call last):
  File "<input>", line 25, in <module>
  File "D:\dev\dfvfs\dfvfs\file_io\encrypted_stream_io.py", line 321, in seek
    offset += self._decrypted_stream_size
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/323820043/

**Comment by joachimmetz** [comment]
Fixes merged as https://github.com/log2timeline/dfvfs/commit/a889480caea51b5580ce140c2628683525086495

Thx for flagging and fixing this
