### ISSUE TITLE
ImportError using dfvfs.vfs.file_entry

### ISSUE THREAD

**Issue by DeKe42** [log2timeline/dfvfs#261]
Hi,

I'm trying to use some of dfvfs's functions from my own python code. I'm running into issues when doing

`import dfvfs.vfs.file_entry`

I get the following errors:

```
Traceback (most recent call last):
  File "/opt/.pycharm_helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/opt/.pycharm_helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/.pycharm_helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/project/triageworker.py", line 11, in <module>
    import dfvfs_utils
  File "/opt/project/dfvfs_utils.py", line 11, in <module>
    import dfvfs.vfs.file_entry
  File "/usr/lib/python2.7/site-packages/dfvfs/vfs/file_entry.py", line 14, in <module>
    from dfvfs.resolver import resolver
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/__init__.py", line 9, in <module>
    from dfvfs.resolver import compressed_stream_resolver_helper
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/compressed_stream_resolver_helper.py", line 8, in <module>
    import dfvfs.vfs.compressed_stream_file_system
  File "/usr/lib/python2.7/site-packages/dfvfs/vfs/compressed_stream_file_system.py", line 9, in <module>
    from dfvfs.vfs import compressed_stream_file_entry
  File "/usr/lib/python2.7/site-packages/dfvfs/vfs/compressed_stream_file_entry.py", line 9, in <module>
    from dfvfs.vfs import root_only_file_entry
  File "/usr/lib/python2.7/site-packages/dfvfs/vfs/root_only_file_entry.py", line 6, in <module>
    from dfvfs.vfs import file_entry
ImportError: cannot import name file_entry
```

Is this a problem because of the circular dependency?

I am using dfvfs inside the plaso docker container, so dependencies should not be an issue. If I work around needing those imports, everything works fine.

Let me know if there is a mailing list or something similar that might be more appropiate for questions like this.

Thanks
Demian

**Comment by joachimmetz** [comment]
> Let me know if there is a mailing list or something similar that might be more appropiate for questions like this.

Posting the question here is fine

> Is this a problem because of the circular dependency?

Looks like a circular dependency; I'm wondering why this is surfacing on your configuration. Does the issue surface outside of PyCharm?

**Comment by Onager** [comment]
I can repro this without pycharm:
```
[1]: from dfvfs.vfs import file_entry
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2ec1e3c526f7> in <module>()
----> 1 from dfvfs.vfs import file_entry

/home/onager/virtualenvs/plaso27/local/lib/python2.7/site-packages/dfvfs/vfs/file_entry.py in <module>()
     12 from dfvfs.lib import definitions
     13 from dfvfs.lib import py2to3
---> 14 from dfvfs.resolver import resolver
     15 from dfvfs.vfs import vfs_stat
     16 

/home/onager/virtualenvs/plaso27/local/lib/python2.7/site-packages/dfvfs/resolver/__init__.py in <module>()
      7   pass
      8 
----> 9 from dfvfs.resolver import compressed_stream_resolver_helper
     10 from dfvfs.resolver import cpio_resolver_helper
     11 from dfvfs.resolver import data_range_resolver_helper

/home/onager/virtualenvs/plaso27/local/lib/python2.7/site-packages/dfvfs/resolver/compressed_stream_resolver_helper.py in <module>()
      6 # This is necessary to prevent a circular import.
      7 import dfvfs.file_io.compressed_stream_io
----> 8 import dfvfs.vfs.compressed_stream_file_system
      9 
     10 from dfvfs.lib import definitions

/home/onager/virtualenvs/plaso27/local/lib/python2.7/site-packages/dfvfs/vfs/compressed_stream_file_system.py in <module>()
      7 from dfvfs.lib import errors
      8 from dfvfs.path import compressed_stream_path_spec
----> 9 from dfvfs.vfs import compressed_stream_file_entry
     10 from dfvfs.vfs import root_only_file_system
     11 

/home/onager/virtualenvs/plaso27/local/lib/python2.7/site-packages/dfvfs/vfs/compressed_stream_file_entry.py in <module>()
      7 from dfvfs.lib import errors
      8 from dfvfs.resolver import resolver
----> 9 from dfvfs.vfs import root_only_file_entry
     10 from dfvfs.vfs import vfs_stat
     11 

/home/onager/virtualenvs/plaso27/local/lib/python2.7/site-packages/dfvfs/vfs/root_only_file_entry.py in <module>()
      4 from __future__ import unicode_literals
      5 
----> 6 from dfvfs.vfs import file_entry
      7 
      8 

ImportError: cannot import name file_entry
```

**Comment by joachimmetz** [comment]
So dfvfs.vfs.file_entry contains an interface class, not really intended for usage outside dfvfs. That that are potential circular import issue with dfvfs is known. Maybe Python relative imports can address this issue.

**Comment by DeKe42** [comment]
Thanks for checking. Yes, it is relatively easy to work around this dependency.

I wanted a helper function to be able to handle `PathSpec ` as well as `FileEntry` objects, so I tried to use `isinstance` which needs the import.

**Comment by joachimmetz** [comment]
https://codereview.appspot.com/335570043/

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/dfvfs/commit/e5a97c51f22c2852978f9d20f00c5aad96972917 should address this.
