### ISSUE TITLE
Unicode problem in os_file_system

### ISSUE THREAD

**Issue by Onager** [log2timeline/dfvfs#31]
```
2015-06-09 21:59:48,193 [ERROR] (Collector ) PID:15849 <multi_process> 'ascii' codec can't decode byte 0xee in position 1: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/onager/code/plaso/plaso/multi_processing/multi_process.py", line 274, in _Main
    self._collector.Collect(self._source_path_specs)
  File "/home/onager/code/plaso/plaso/engine/collector.py", line 113, in Collect
    source_path_spec, find_specs=self._filter_find_specs)
  File "/home/onager/code/plaso/plaso/engine/collector.py", line 93, in _ProcessPathSpec
    self._ProcessFileSystem(path_spec, find_specs=find_specs)
  File "/home/onager/code/plaso/plaso/engine/collector.py", line 59, in _ProcessFileSystem
    self._fs_collector.Collect(file_system, path_spec, find_specs=find_specs)
  File "/home/onager/code/plaso/plaso/engine/collector.py", line 298, in Collect
    self._ProcessDirectory(file_entry)
  File "/home/onager/code/plaso/plaso/engine/collector.py", line 272, in _ProcessDirectory
    self._ProcessDirectory(sub_file_entry)
  File "/home/onager/code/plaso/plaso/engine/collector.py", line 272, in _ProcessDirectory
    self._ProcessDirectory(sub_file_entry)
  File "/home/onager/code/plaso/plaso/engine/collector.py", line 272, in _ProcessDirectory
    self._ProcessDirectory(sub_file_entry)
  File "/home/onager/code/plaso/plaso/engine/collector.py", line 272, in _ProcessDirectory
    self._ProcessDirectory(sub_file_entry)
  File "/home/onager/code/plaso/plaso/engine/collector.py", line 272, in _ProcessDirectory
    self._ProcessDirectory(sub_file_entry)
  File "/home/onager/code/plaso/plaso/engine/collector.py", line 272, in _ProcessDirectory
    self._ProcessDirectory(sub_file_entry)
  File "/home/onager/code/plaso/plaso/engine/collector.py", line 272, in _ProcessDirectory
    self._ProcessDirectory(sub_file_entry)
  File "/home/onager/code/plaso/plaso/engine/collector.py", line 272, in _ProcessDirectory
    self._ProcessDirectory(sub_file_entry)
  File "/home/onager/code/plaso/plaso/engine/collector.py", line 220, in _ProcessDirectory
    for sub_file_entry in file_entry.sub_file_entries:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/os_file_entry.py", line 209, in sub_file_entries
    for path_spec in self._directory.entries:
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/file_entry.py", line 42, in entries
    for entry in self._EntriesGenerator():
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/os_file_entry.py", line 45, in _EntriesGenerator
    location, directory_entry])
  File "/usr/lib/python2.7/dist-packages/dfvfs/vfs/os_file_system.py", line 184, in JoinPath
    segment.split(self.PATH_SEPARATOR) for segment in path_segments]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xee in position 1: ordinal not in range(128)
```

**Comment by Onager** [comment]
It seems that dfvfs was parsing a broken symlink at the time.

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/dfvfs/blob/master/dfvfs/vfs/os_file_system.py#L184

That would mean path_segments is non Unicode. I assume you have the source directory?

**Comment by Onager** [comment]
Yep, I do, and it is non-unicode, 0xee, per the backtrace.

**Comment by joachimmetz** [comment]
I would need to know what Python's file system encoding is, for this file system.
If that is non-UTF8 we likely need to use that to decode symbolic links.
