### ISSUE TITLE
Unsupported inode 0 in TSKPathSpec

### ISSUE THREAD

**Issue by devgc** [log2timeline/dfvfs#320]
Creating a TSKPathSpec with inode of 0 fails even though this is a valid inode.

The following example code should open the MFT file entry provided `\\.\C:` is an NTFS volume. 

```python
from dfvfs.path import factory
from dfvfs.lib import definitions
from dfvfs.resolver import resolver


def main():
    os_path_spec = factory.Factory.NewPathSpec(
        definitions.TYPE_INDICATOR_OS,
        location="\\\\.\\C:"
    )

    logical_path_spec = factory.Factory.NewPathSpec(
        definitions.TYPE_INDICATOR_TSK,
        location=u'/',
        parent=os_path_spec
    )

    file_system = resolver.Resolver.OpenFileSystem(
        logical_path_spec
    )

    mft_inode_path_spec = factory.Factory.NewPathSpec(
        definitions.TYPE_INDICATOR_TSK,
        inode=0,
        parent=os_path_spec
    )

    mft_file_entry = file_system.GetFileEntryByPathSpec(
        mft_inode_path_spec
    )

    mft_object = mft_file_entry.GetFileObject()
    first_4_bytes = mft_object.read(4)

    print(first_4_bytes)


if __name__ == "__main__":
    main()
    
```

But it errors out with:
```
Traceback (most recent call last):
  File "C:/debug/dfvfs_open_inode_0.py", line 36, in <module>
    main()
  File "C:/debug/dfvfs_open_inode_0.py", line 25, in main
    parent=os_path_spec
  File "C:\Python27\lib\site-packages\dfvfs\path\factory.py", line 116, in NewPathSpec
    return path_spec_type(**kwargs)
  File "C:\Python27\lib\site-packages\dfvfs\path\tsk_path_spec.py", line 40, in __init__
    raise ValueError('Missing inode and location, or parent value.')
ValueError: Missing inode and location, or parent value.
```

This can be fixed by testing if inode is None rather than a *False* evaluation. The error occurs because 0 evaluates to False.
Changing the `__init__` validation for **TSKPathSpec** to the following fixes the issue:

*Proposed Change:*
```python
    if (inode is None and not location) or not parent:
      raise ValueError('Missing inode and location, or parent value.')
```

*Current Code:*
```python
    if (not inode and not location) or not parent:
      raise ValueError('Missing inode and location, or parent value.')
```

Changing the `tsk_path_spec.py` with the proposed change does allow the above code to run and print "FILE". But, it looks like maybe some changes would need to be applied else where because the TSKFileEntry does not seem to have all of its attributes updated (such as TSKFileEntry._name).

**Comment by joachimmetz** [comment]
thx for the report. an inode number on ext should not be 0, but libtsk indeed overloads this value.
