### ISSUE TITLE
Stat Errors on Windows Logical and Physical Drives

### ISSUE THREAD

**Issue by devgc** [log2timeline/dfvfs#381]
Errors occur when trying to use a logical (\\\\.\\C:) or physical drive (\\\\.\\PHYSICALDRIVE0) with the SourceScanner.  This is due to the handles not having stat objects.

Example script to produce the errors on a Windows system:
```python
import traceback
from dfvfs.helpers import source_scanner


def scan_win_physical_drive():
    scan_path_spec = None
    scanner = source_scanner.SourceScanner()
    scan_context = source_scanner.SourceScannerContext()
    scan_context.OpenSourcePath("\\\\.\\PHYSICALDRIVE0")

    scanner.Scan(
        scan_context,
        scan_path_spec=scan_path_spec
    )


def scan_win_logical_volume():
    scan_path_spec = None
    scanner = source_scanner.SourceScanner()
    scan_context = source_scanner.SourceScannerContext()
    scan_context.OpenSourcePath("\\\\.\\C:")

    scanner.Scan(
        scan_context,
        scan_path_spec=scan_path_spec
    )


def main():
    print("Attempting to scan PHYSICALDRIVE0")
    try:
        scan_win_physical_drive()
    except Exception as error:
        trace_str = traceback.format_exc()
        error_msg = "{}".format(
            trace_str
        )
        error_msg = error_msg.replace("\r", "\n")
        print(error_msg)

    print("Attempting to scan \\\\.\\C:")
    try:
        scan_win_logical_volume()
    except Exception as error:
        trace_str = traceback.format_exc()
        error_msg = "{}".format(
            trace_str
        )
        error_msg = error_msg.replace("\r", "\n")
        print(error_msg)


if __name__ == "__main__":
    main()
```

Output from the example script:
```
Attempting to scan PHYSICALDRIVE0
Traceback (most recent call last):
  File "windows_live_tests.py", line 32, in main
    scan_win_physical_drive()
  File "windows_live_tests.py", line 13, in scan_win_physical_drive
    scan_path_spec=scan_path_spec
  File "C:\Python27\lib\site-packages\dfvfs\helpers\source_scanner.py", line 662, in Scan
    self._ScanNode(scan_context, scan_node, auto_recurse=auto_recurse)
  File "C:\Python27\lib\site-packages\dfvfs\helpers\source_scanner.py", line 424, in _ScanNode
    if system_level_file_entry.IsDirectory():
  File "C:\Python27\lib\site-packages\dfvfs\vfs\file_entry.py", line 492, in IsDirectory
    self._stat_object = self._GetStat()
  File "C:\Python27\lib\site-packages\dfvfs\vfs\os_file_entry.py", line 177, in _GetStat
    stat_object = super(OSFileEntry, self)._GetStat()
  File "C:\Python27\lib\site-packages\dfvfs\vfs\file_entry.py", line 206, in _GetStat
    access_time = self.access_time
  File "C:\Python27\lib\site-packages\dfvfs\vfs\os_file_entry.py", line 211, in access_time
    timestamp = int(self._stat_info.st_atime)
AttributeError: 'NoneType' object has no attribute 'st_atime'

Attempting to scan \\.\C:
Traceback (most recent call last):
  File "windows_live_tests.py", line 43, in main
    scan_win_logical_volume()
  File "windows_live_tests.py", line 25, in scan_win_logical_volume
    scan_path_spec=scan_path_spec
  File "C:\Python27\lib\site-packages\dfvfs\helpers\source_scanner.py", line 662, in Scan
    self._ScanNode(scan_context, scan_node, auto_recurse=auto_recurse)
  File "C:\Python27\lib\site-packages\dfvfs\helpers\source_scanner.py", line 424, in _ScanNode
    if system_level_file_entry.IsDirectory():
  File "C:\Python27\lib\site-packages\dfvfs\vfs\file_entry.py", line 492, in IsDirectory
    self._stat_object = self._GetStat()
  File "C:\Python27\lib\site-packages\dfvfs\vfs\os_file_entry.py", line 177, in _GetStat
    stat_object = super(OSFileEntry, self)._GetStat()
  File "C:\Python27\lib\site-packages\dfvfs\vfs\file_entry.py", line 206, in _GetStat
    access_time = self.access_time
  File "C:\Python27\lib\site-packages\dfvfs\vfs\os_file_entry.py", line 211, in access_time
    timestamp = int(self._stat_info.st_atime)
AttributeError: 'NoneType' object has no attribute 'st_atime'
```

Currently I get around this by doing something like following:
```python
def dfvfs_physical_shim():
    """This is a shim that is needed when a Physical volume is used.
    The _stat_info is not available when using volumes.
    """
    from dfvfs.vfs import os_file_entry

    @property
    def access_time(self):
        """dfdatetime.DateTimeValues: access time or None if not available."""
        # SHIM - Return None if _stat_info does not exist
        if not self._stat_info:
            return None
        # END SHIM
        timestamp = int(self._stat_info.st_atime)
        return dfdatetime_posix_time.PosixTime(timestamp=timestamp)

    @property
    def change_time(self):
        """dfdatetime.DateTimeValues: change time or None if not available."""
        # SHIM - Return None if _stat_info does not exist
        if not self._stat_info:
            return None
        # END SHIM
        timestamp = int(self._stat_info.st_ctime)
        return dfdatetime_posix_time.PosixTime(timestamp=timestamp)

    @property
    def modification_time(self):
        """dfdatetime.DateTimeValues: modification time or None if not available."""
        # SHIM - Return None if _stat_info does not exist
        if not self._stat_info:
            return None
        # END SHIM
        timestamp = int(self._stat_info.st_mtime)
        return dfdatetime_posix_time.PosixTime(timestamp=timestamp)

    os_file_entry.OSFileEntry.access_time = access_time
    os_file_entry.OSFileEntry.change_time = change_time
    os_file_entry.OSFileEntry.modification_time = modification_time
```

If changing the OSFileEntry's property functions is a valid solution (as seen above) I can create a pull request. I wouldn't mind learning to contributed to DFVFS. Otherwise, I leave it to your discretion.

**Comment by joachimmetz** [comment]
the use of stat has been on the deprecation list for a while https://github.com/log2timeline/dfvfs/issues/52 let me have a look on how to best change this.

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/dfvfs/pull/384

**Comment by joachimmetz** [comment]
More work on removing stat https://github.com/log2timeline/dfvfs/pull/470

**Comment by joachimmetz** [comment]
stat has been removed
