### ISSUE TITLE
Look into failing test

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dfvfs#424]
```
======================================================================
ERROR: testCopyFromDateTimeString (vfs.tsk_file_entry.TSKTimeTest)
Tests the CopyFromDateTimeString function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dfvfs/tests/vfs/tsk_file_entry.py", line 33, in testCopyFromDateTimeString
    tsk_time_object.CopyFromDateTimeString('2010-08-12 21:06:31.546875')
  File "./dfvfs/vfs/tsk_file_entry.py", line 108, in CopyFromDateTimeString
    year, month, day_of_month, hours, minutes, seconds)
TypeError: _GetNumberOfSecondsFromElements() missing 1 required positional argument: 'time_zone_offset'
----------------------------------------------------------------------
```

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/dfvfs/pull/425
