### ISSUE TITLE
dfvfs.lib.errors.BackEndError: Unable to open file system with error: pyvshadow_volume_open_file_object

### ISSUE THREAD

**Issue by sorchaa** [log2timeline/dfvfs#613]
Hello,
I encountered this error when running log2timeline on some images made from guymaguer. I tried the same command on the original hard drive with the same result. On other disks with the same version of guymaguer log2timeline works as expected. the images in ewf format are mountable and perfectly readable.

Version of log2timeline :
# log2timeline.py -V
plaso - log2timeline version 20211024

Version of dfvfs:
# pip3 show dfvfs
Name: dfvfs
Version: 20211017
Summary: Digital Forensics Virtual File System (dfVFS).
Home-page: https://github.com/log2timeline/dfvfs
Author: None
Author-email: None
License: Apache License, Version 2.0
Location: /usr/local/lib/python3.9/dist-packages
Requires: 
Required-by: 

Error :
`# log2timeline.py --storage_file mft.plaso --parsers mft -f /mnt/mft_log2timeline.txt --no_vss /mnt/ewf/ewf1
2021-11-15 08:55:30,937 [INFO] (MainProcess) PID:6577 <data_location> Determined data location: /usr/local/share/plaso
2021-11-15 08:55:30,945 [INFO] (MainProcess) PID:6577 <artifact_definitions> Determined artifact definitions path: /usr/local/share/artifacts
Checking availability and versions of dependencies.
[OK]

The following partitions were found:

Identifier      Offset (in bytes)               Size (in bytes)
p1              1048576 (0x00100000)            500.0MiB / 524.3MB (524287488 B)
p2              525336576 (0x1f500000)          128.0MiB / 134.2MB (134217216 B)
p3              659554304 (0x27500000)          463.8GiB / 498.0GB (497959221760 B)
p4              498618859520 (0x7418000000)     508.0MiB / 532.7MB (532676096 B)
p5              499151536128 (0x7437c00000)     450.0MiB / 471.9MB (471858688 B)
p6              499623395328 (0x7453e00000)     11.6GiB / 12.5GB (12486442496 B)

Please specify the identifier of the partition that should be
processed. All partitions can be defined as: "all". Note that you can
abort with Ctrl^C.

Partition identifier(s): 3
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/dfvfs/resolver/resolver.py", line 168, in OpenFileSystem
    file_system.Open()
  File "/usr/local/lib/python3.9/dist-packages/dfvfs/vfs/file_system.py", line 257, in Open
    self._Open(mode=mode)
  File "/usr/local/lib/python3.9/dist-packages/dfvfs/vfs/vshadow_file_system.py", line 63, in _Open
    vshadow_volume.open_file_object(file_object)
OSError: pyvshadow_volume_open_file_object: unable to open volume. libvshadow_ntfs_volume_header_read_file_io_handle: unable to read NTFS volume header data at offset: 497959221760 (0x73f0aeba00). libvshadow_volume_open_read_ntfs_volume_headers: unable to read backup NTFS volume header. libvshadow_volume_open_read: unable to read NTFS volume headers. libvshadow_volume_open_file_io_handle: unable to read from file IO handle.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/log2timeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('plaso==20211024', 'log2timeline.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.9/dist-packages/plaso-20211024-py3.9.egg/EGG-INFO/scripts/log2timeline.py", line 99, in <module>
    if not Main():
  File "/usr/local/lib/python3.9/dist-packages/plaso-20211024-py3.9.egg/EGG-INFO/scripts/log2timeline.py", line 73, in Main
    tool.ExtractEventsFromSources()
  File "/usr/local/lib/python3.9/dist-packages/plaso/cli/extraction_tool.py", line 651, in ExtractEventsFromSources
    self.ScanSource(self._source_path)
  File "/usr/local/lib/python3.9/dist-packages/plaso/cli/storage_media_tool.py", line 642, in ScanSource
    base_path_specs = volume_scanner_object.GetBasePathSpecs(
  File "/usr/local/lib/python3.9/dist-packages/dfvfs/helpers/volume_scanner.py", line 689, in GetBasePathSpecs
    return self._GetBasePathSpecs(scan_context, options)
  File "/usr/local/lib/python3.9/dist-packages/plaso/cli/storage_media_tool.py", line 224, in _GetBasePathSpecs
    self._ScanVolume(scan_context, sub_scan_node, options, base_path_specs)
  File "/usr/local/lib/python3.9/dist-packages/dfvfs/helpers/volume_scanner.py", line 607, in _ScanVolume
    self._ScanVolume(scan_context, sub_scan_node, options, base_path_specs)
  File "/usr/local/lib/python3.9/dist-packages/dfvfs/helpers/volume_scanner.py", line 582, in _ScanVolume
    self._ScanVolumeSystemRoot(
  File "/usr/local/lib/python3.9/dist-packages/plaso/cli/storage_media_tool.py", line 309, in _ScanVolumeSystemRoot
    volume_system.Open(scan_node.path_spec)
  File "/usr/local/lib/python3.9/dist-packages/dfvfs/volume/volume_system.py", line 290, in Open
    self._file_system = resolver.Resolver.OpenFileSystem(path_spec)
  File "/usr/local/lib/python3.9/dist-packages/dfvfs/resolver/resolver.py", line 170, in OpenFileSystem
    raise errors.BackEndError(
dfvfs.lib.errors.BackEndError: Unable to open file system with error: pyvshadow_volume_open_file_object: unable to open volume. libvshadow_ntfs_volume_header_read_file_io_handle: unable to read NTFS volume header data at offset: 497959221760 (0x73f0aeba00). libvshadow_volume_open_read_ntfs_volume_headers: unable to read backup NTFS volume header. libvshadow_volume_open_read: unable to read NTFS volume headers. libvshadow_volume_open_file_io_handle: unable to read from file IO handle.
`

If you need something more for debugging, it will be with pleasure.
Have a nice day,

**Comment by joachimmetz** [comment]
>  pip3 show dfvfs

First of all using pip without virtualenv is **NOT** a recommended installation method.

```
OSError: pyvshadow_volume_open_file_object: unable to open volume.
libvshadow_ntfs_volume_header_read_file_io_handle: unable to read NTFS volume header data at offset: 497959221760 (0x73f0aeba00).
libvshadow_volume_open_read_ntfs_volume_headers: unable to read backup NTFS volume header.
libvshadow_volume_open_read: unable to read NTFS volume headers.
libvshadow_volume_open_file_io_handle: unable to read from file IO handle.
```

This error indicates that libvshadow is not able to find the back up NTFS volume header.

* First check if all your data is there.
* Provide me with more context on what images this is failing (volume only images?)
