### ISSUE TITLE
CI tests failing with: ImportError: DLL load failed while importing _openssl

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dfvfs#706]
Looks like cryptography depends on pyOpenSSL in some cases

```
======================================================================
ERROR: testOpenClosePathSpec (file_io.encrypted_stream_io.RC4EncryptedStreamWithKeyChainTest)
Test the open and close functionality using a path specification.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\dfvfs\tests\file_io\encrypted_stream_io.py", line 361, in testOpenClosePathSpec
    self._TestGetSizeFileObject(file_object)
  File "C:\projects\dfvfs\.\tests\file_io\test_lib.py", line 634, in _TestGetSizeFileObject
    self.assertEqual(file_object.get_size(), 1247)
  File "C:\projects\dfvfs\.\dfvfs\file_io\encrypted_stream_io.py", line 349, in get_size
    self._decrypted_stream_size = self._GetDecryptedStreamSize()
  File "C:\projects\dfvfs\.\dfvfs\file_io\encrypted_stream_io.py", line 74, in _GetDecryptedStreamSize
    self._decrypter = self._GetDecrypter()
  File "C:\projects\dfvfs\.\dfvfs\file_io\encrypted_stream_io.py", line 63, in _GetDecrypter
    return encryption_manager.EncryptionManager.GetDecrypter(
  File "C:\projects\dfvfs\.\dfvfs\encryption\manager.py", line 47, in GetDecrypter
    return decrypter(**kwargs)
  File "C:\projects\dfvfs\.\dfvfs\encryption\rc4_decrypter.py", line 33, in __init__
    backend = backends.default_backend()
  File "C:\Python310-x64\lib\site-packages\cryptography\hazmat\backends\__init__.py", line 16, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Python310-x64\lib\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Python310-x64\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 82, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "C:\Python310-x64\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed while importing _openssl: The specified module could not be found.
======================================================================
```

**Comment by joachimmetz** [comment]
Let's see if the latest version of cryptography fixes the issue. Otherwise possible alternative is to ship pyopenssl.

**Comment by joachimmetz** [comment]
Looks like cryptography 38 does not properly build a MSI

**Comment by joachimmetz** [comment]
Issue still persists in cryptography 38 there is a bindings/_openssl.pyi file that imports typing

**Comment by joachimmetz** [comment]
Looks like pyOpenSSL imports cryptography

**Comment by joachimmetz** [comment]
For now will catch the issues in the test, longer term it might be an idea to move away from cryptography
