### ISSUE TITLE
compressed_stream_io: fix out of bounds issue

### ISSUE THREAD

**Issue by joachimmetz** [log2timeline/dfvfs#8]
```
Traceback (most recent call last):
  File "/Projects/plaso/plaso/engine/worker.py", line 126, in _ParseFileEntryWithParser
    parser_object.Parse(self._parser_context, file_entry)
  File "/Projects/plaso/plaso/parsers/text_parser.py", line 471, in Parse
    row = reader.next()
  File "/usr/lib/python2.7/csv.py", line 108, in next
    row = self.reader.next()
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/text_file.py", line 71, in __iter__
    line = self.readline()
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/text_file.py", line 179, in readline
    lines_data = self._ReadLinesData(size)
  File "/usr/lib/python2.7/dist-packages/dfvfs/helpers/text_file.py", line 121, in _ReadLinesData
    read_buffer = self._file_object.read(read_size)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/file_object_io.py", line 132, in read
    return self._file_object.read(size)
  File "/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py", line 370, in read
    self._uncompressed_data[self._uncompressed_data_offset]])
```

**Comment by joachimmetz** [comment]
/usr/lib/python2.7/dist-packages/dfvfs/file_io/compressed_stream_io.py:353
```
    if (self._uncompressed_stream_size == 0 or
        self._current_offset >= self._uncompressed_stream_size):
      return b''
```
